path : C:\Users\LENOVO\Desktop\
train : currency/train
val : currency/test

names:
 0: 500 taka
 1: Fifty taka
 2: Five Hundred taka
 3: Five Taka
 4: One Taka
 5: One Thousand taka
 6: Ten Taka
 7: Twenty
 8: currency
 9: one hundred taka
 10: two taka